version: '3'

services: 

  mysql_lib:
    container_name: mysql_lib
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lib_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '5306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      
  php_fpm_lib:
    build:
      context: ../docker/php-fpm
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:secret@mysql_lib:3306/lib_db?serverVersion=8
    container_name: php_fpm_lib
    restart: unless-stopped
    volumes:
      - ../src:/var/www
      - ../data/lib/uploads:/var/www/public/uploads
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - mysql_lib
    links:
      - mysql_lib
  nginx_lib:
    build:
      context: ../docker/nginx
    volumes:
      - ../src:/var/www
      - ../data/lib/uploads:/var/www/public/uploads
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../docker/nginx/sites/:/etc/nginx/sites-available
      - ../docker/nginx/conf.d/:/etc/nginx/conf.d
      - ../docker/logs:/var/log
      - ../docker/nginx/ssl:/etc/nginx/ssl
    container_name: nginx_lib
    restart: unless-stopped
    depends_on:
      - php_fpm_lib
    ports:
      - "4499:443"

