#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Загрузка маршрутов

authors:
    #Для работы с авторами
    resource: 'routes/api_v1/authors.yaml'

books:
    #Для работы с авторами
    resource: 'routes/api_v1/books.yaml'

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }
